require('dotenv').config();
const { writeFile, existsSync, mkdirSync } = require('fs');

const envDirectory = './src/environments';
const targetPath = './src/environments/environments.ts';

function writeFileUsingFS(targetPath, environmentFileContent) {
  writeFile(targetPath, environmentFileContent, function (err) {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`wrote variables to ${targetPath}`);
    }
  });
}

// creates the `environments` directory if it does not exist
if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}

writeFileUsingFS(targetPath, '');

const environmentFileContent = `
  // This file was autogenerated by dynamically running createEnv.ts and using dotenv for managing API key secrecy
  export const environments = {
    API_URL: '${process.env.API_URL}'
  };
`;

writeFileUsingFS(targetPath, environmentFileContent); // appending data into the target file

